- name: Ensure packages needed for mariadb are present
  apt: name={{ item }} state=present
  with_items:
    - mariadb-server
    - python-mysqldb # for ansible to connect
    - libmysqlclient-dev # needed for mariadb client bindings

- name: Ensure that mariadb is started
  service: name=mysql state=started enabled=yes

