- name: Ensure packages needed for mariadb are present
  apt: name={{ item }} state=present
  with_items: "{{ mariadb_packages }}"

- name: Ensure that mariadb is started
  service: name=mysql state=started enabled=yes

